use crate::types::{DuplicateGroup, ScanStats};
use colored::Colorize;
use std::fs;
use std::io::Write;
use std::path::Path;

/// 把字节数格式化为人类可读的字符串
fn format_size(bytes: u64) -> String {
    const UNITS: &[&str] = &["B", "KB", "MB", "GB", "TB"];
    let mut size = bytes as f64;
    let mut unit_idx = 0;

    while size >= 1000.0 && unit_idx < UNITS.len() - 1 {
        size /= 1000.0;
        unit_idx += 1;
    }

    if unit_idx == 0 {
        format!("{bytes} B")
    } else if size < 10.0 {
        format!("{size:.1} {}", UNITS[unit_idx])
    } else {
        format!("{size:.0} {}", UNITS[unit_idx])
    }
}

/// 彩色终端表格输出
pub fn print_table(groups: &[DuplicateGroup], stats: &ScanStats) {
    if groups.is_empty() {
        println!("\n{}", "No duplicate files found.".green().bold());
        println!(
            "Scanned {} files ({}).\n",
            stats.total_files,
            format_size(stats.total_size)
        );
        return;
    }

    println!("\n{}", "=== Duplicate Files Report ===".cyan().bold());
    println!();

    for (i, group) in groups.iter().enumerate() {
        let size_str = format_size(group.size);
        let waste = format_size(group.size * (group.files.len() as u64 - 1));

        println!(
            "{} {} × {} {} — {}: {}",
            format!("Group {}", i + 1).yellow().bold(),
            size_str,
            format!("{} files", group.files.len()).bold(),
            "duplicates".dimmed(),
            "waste".red().bold(),
            waste.red().bold(),
        );

        for (j, file) in group.files.iter().enumerate() {
            if j == 0 {
                println!(
                    "  {} {}",
                    "keep :".green(),
                    file.display().to_string().dimmed()
                );
            } else {
                println!(
                    "  {} {}",
                    "del  :".red(),
                    file.display().to_string().dimmed()
                );
            }
        }
        println!();
    }

    print_summary(stats);
}

fn print_summary(stats: &ScanStats) {
    println!("{}", "─────────────────────────────────────────".dimmed());
    println!("{}", "Scan Summary:".bold());
    println!(
        "  Total files scanned : {}",
        format!("{}", stats.total_files).bold()
    );
    println!(
        "  Total data scanned  : {}",
        format_size(stats.total_size).bold()
    );
    println!(
        "  Duplicate groups    : {}",
        format!("{}", stats.duplicate_groups).yellow().bold()
    );
    println!(
        "  Wasted space        : {}",
        format_size(stats.wasted_bytes).red().bold()
    );

    if stats.wasted_bytes > 0 {
        let pct = (stats.wasted_bytes as f64 / stats.total_size as f64) * 100.0;
        println!(
            "  ({:.1}% of total data is duplicate)",
            format!("{pct:.1}").yellow()
        );
    }
    println!();
}

/// JSON 格式输出
pub fn print_json(groups: &[DuplicateGroup], stats: &ScanStats) -> anyhow::Result<()> {
    #[derive(serde::Serialize)]
    struct JsonOutput<'a> {
        scan_stats: &'a ScanStats,
        duplicate_groups: &'a [DuplicateGroup],
    }

    let output = JsonOutput {
        scan_stats: stats,
        duplicate_groups: groups,
    };

    let json = serde_json::to_string_pretty(&output)?;
    println!("{json}");
    Ok(())
}

/// 生成删除脚本
pub fn generate_delete_script(groups: &[DuplicateGroup], script_path: &Path) -> anyhow::Result<()> {
    if groups.is_empty() {
        println!("No duplicates found — empty script will be generated.");
    }

    let is_windows = cfg!(target_os = "windows");

    let mut script = String::new();

    if is_windows {
        script.push_str("# dupe-killer deletion script (PowerShell)\n");
        script.push_str("# Review carefully before executing!\n");
        script.push_str("# Run: powershell -ExecutionPolicy Bypass -File ");
        script.push_str(&script_path.display().to_string());
        script.push_str("\n\n");
        script.push_str("$ErrorActionPreference = \"Stop\"\n\n");
    } else {
        script.push_str("#!/usr/bin/env bash\n");
        script.push_str("# dupe-killer deletion script\n");
        script.push_str("# Review carefully before executing!\n");
        script.push_str("# Run: bash ");
        script.push_str(&script_path.display().to_string());
        script.push_str("\n\n");
        script.push_str("set -euo pipefail\n\n");
    }

    script.push_str(&format!(
        "# Generated by dupe-killer v{}\n",
        env!("CARGO_PKG_VERSION")
    ));
    script.push_str(&format!(
        "# {} duplicate group(s) | {} reclaimable\n",
        groups.len(),
        format_size(
            groups
                .iter()
                .map(|g| g.size * (g.files.len() as u64 - 1))
                .sum()
        )
    ));
    script.push_str("#\n");
    script.push_str("# Each section shows: hash, size, files\n");
    script.push_str("# The FIRST file is KEPT; all others are DELETED\n\n");

    for (i, group) in groups.iter().enumerate() {
        script.push_str(&format!(
            "# ── Group {}: {} × {} files (hash: {}) ──\n",
            i + 1,
            format_size(group.size),
            group.files.len(),
            group.hash,
        ));

        for (j, file) in group.files.iter().enumerate() {
            let escaped = file.display().to_string();
            if j == 0 {
                script.push_str(&format!("# KEEP: {escaped}\n"));
            } else if is_windows {
                script.push_str(&format!("Remove-Item -LiteralPath \"{escaped}\" -Force\n"));
            } else {
                script.push_str(&format!("rm -f \"{escaped}\"\n"));
            }
        }
        script.push('\n');
    }

    if is_windows {
        script.push_str("Write-Host \"Done. Deleted ");
        script.push_str(&format!(
            "{} files.\"",
            groups.iter().map(|g| g.files.len() as u64 - 1).sum::<u64>()
        ));
        script.push('\n');
        script.push_str("Remove-Item -LiteralPath $PSCommandPath -Force\n");
    } else {
        script.push_str(&format!(
            "echo \"Done. Deleted {} files.\"\n",
            groups.iter().map(|g| g.files.len() as u64 - 1).sum::<u64>()
        ));
        script.push_str("rm -f \"$0\"\n");
    }

    let mut file = fs::File::create(script_path)?;

    // 写入 UTF-8 BOM，让 PowerShell 正确识别中文路径
    if is_windows {
        file.write_all(&[0xEF, 0xBB, 0xBF])?;
    }
    file.write_all(script.as_bytes())?;

    // Unix 下加可执行权限
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = file.metadata()?.permissions();
        perms.set_mode(0o755);
        fs::set_permissions(script_path, perms)?;
    }

    println!("{} 删除脚本已写入 {}", "✓".green(), script_path.display());
    println!("  {} 请仔细审核脚本后再执行。", "⚠".yellow());
    if is_windows {
        println!(
            "  执行: powershell -ExecutionPolicy Bypass -File {}",
            script_path.display()
        );
    } else {
        println!("  执行: bash {}", script_path.display());
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_format_size_bytes() {
        assert_eq!(format_size(0), "0 B");
        assert_eq!(format_size(500), "500 B");
    }

    #[test]
    fn test_format_size_kb() {
        assert_eq!(format_size(1_500), "1.5 KB");
        assert_eq!(format_size(50_000), "50 KB");
    }

    #[test]
    fn test_format_size_mb() {
        assert_eq!(format_size(1_500_000), "1.5 MB");
        assert_eq!(format_size(75_000_000), "75 MB");
    }

    #[test]
    fn test_format_size_gb() {
        assert_eq!(format_size(1_500_000_000), "1.5 GB");
    }
}
